// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBogqBx_4Ui4qtgGNJJt_bOZtxpsdmddPs',
    appId: '1:996719360587:web:23829404a22b53fc292bce',
    messagingSenderId: '996719360587',
    projectId: 'incomecalculator-1b65e',
    authDomain: 'incomecalculator-1b65e.firebaseapp.com',
    databaseURL: 'https://incomecalculator-1b65e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'incomecalculator-1b65e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAPltqKpwgptWctmwTvR4J0n4eCyUN0tE',
    appId: '1:996719360587:android:843b355d7fd970e7292bce',
    messagingSenderId: '996719360587',
    projectId: 'incomecalculator-1b65e',
    databaseURL: 'https://incomecalculator-1b65e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'incomecalculator-1b65e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWfKnzAUAc7Uu4HYB91ggeXE4ZAuErevg',
    appId: '1:996719360587:ios:c6e486a4eef5dfeb292bce',
    messagingSenderId: '996719360587',
    projectId: 'incomecalculator-1b65e',
    databaseURL: 'https://incomecalculator-1b65e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'incomecalculator-1b65e.firebasestorage.app',
    iosBundleId: 'com.example.expenseCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWfKnzAUAc7Uu4HYB91ggeXE4ZAuErevg',
    appId: '1:996719360587:ios:c6e486a4eef5dfeb292bce',
    messagingSenderId: '996719360587',
    projectId: 'incomecalculator-1b65e',
    databaseURL: 'https://incomecalculator-1b65e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'incomecalculator-1b65e.firebasestorage.app',
    iosBundleId: 'com.example.expenseCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBogqBx_4Ui4qtgGNJJt_bOZtxpsdmddPs',
    appId: '1:996719360587:web:d2aed5886a9ce0f1292bce',
    messagingSenderId: '996719360587',
    projectId: 'incomecalculator-1b65e',
    authDomain: 'incomecalculator-1b65e.firebaseapp.com',
    databaseURL: 'https://incomecalculator-1b65e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'incomecalculator-1b65e.firebasestorage.app',
  );

}